#ifndef COMMON_H
#define COMMON_H

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include "tweetnacl.h"

#define MESSAGE "There are strange things done in the midnight sun\n" \
                    "By the men who toil for gold;\n"                 \
                "The Arctic trails have their secret tales\n"         \
                    "That would make your blood run cold;\n"          \
                "The Northern Lights have seen queer sights,\n"       \
                    "But the queerest they ever did see\n"            \
                "Was that night on the marge of Lake Lebarge\n"       \
                    "I cremated Sam McGee.\n"
                                              /* - Robert W. Service */

#define MESSAGE_LEN 304 /* I counted */

/* generated by crypto_box_keypair() */
#define CLIENT_PUB "\xbc\x07\x9f\xfe\xf5\x09\x6b\x2b" \
                   "\xfe\xd3\x8e\xdb\xe5\x26\xc0\xd3" \
                   "\x57\xba\x79\x88\xbf\xff\x9e\x8e" \
                   "\xea\x85\xcf\xd4\xcb\xb0\x7b\x3d"

#define CLIENT_SEC "\x53\xb7\xab\xca\x19\x81\xca\xd7" \
                   "\x6a\x87\x9d\xe3\xa3\x93\xd5\x73" \
                   "\x84\x39\xa5\x10\x3e\x4d\xdf\xde" \
                   "\xea\x19\x25\x01\xc9\xf3\x06\xf6"


/* also generated by crypto_box_keypair() */
#define SERVER_PUB "\xb0\x5c\x49\xda\xc9\xf6\xbc\x86" \
                   "\xcf\x76\xe5\xbd\xca\xe8\x0e\x14" \
                   "\x50\x03\xba\xbb\xa9\x4d\xfc\x6c" \
                   "\x4c\x0a\xeb\xff\x9a\x5c\xba\x31"

#define SERVER_SEC "\x22\x1b\x3e\x9c\xf7\xb0\x94\xdd" \
                   "\xec\xdb\x58\x02\x4f\x54\xa6\xfa" \
                   "\xc9\x0f\xa4\x86\x90\x80\xe7\xf5" \
                   "\xec\xb9\x4d\x87\xdb\xb9\x1e\xfc"

static void
dump(const char *prefix, const uint8_t *buf, size_t len)
{
	size_t i;
	printf("%s\n------------------------------------------------\n", prefix);
	for (i = 0; i < len; i++) {
		printf(" %02x%s", buf[i], (i+1) % 16 == 0 ? "\n" : "");
	}
	if (len % 16 != 0) printf("\n");
	printf("------------------------------------------------\n");
}

/* tweetnacl is a bring-your-own-randomness kinda lib */
int
randombytes(uint8_t *buf, size_t len)
{
	FILE *in;
	int rc;
	in = fopen("/dev/urandom", "r");
	if (!in) return 1;
	rc = fread(buf, len, 1, in) == 1 ? 0 : 1;
	fclose(in);
	return rc;
}

#endif
