/* asm0 - generated by gencode */

#define ARG_NONE      0x00
#define ARG_REGISTER  0x01
#define ARG_NUMBER    0x02
#define ARG_STRING    0x04
#define ARG_LABEL     0x08
#define ARG_FUNCTION  0x10

static struct {
	byte_t      token;
	const char *usage;
	byte_t      opcode;
	byte_t      args[2];
} ASM_SYNTAX[] = {
	{ T_OPCODE_NOOP,          "noop",                                   NOOP,          { ARG_NONE,                           ARG_NONE,                           } },
	{ T_OPCODE_PUSH,          "push %a",                                PUSH,          { ARG_REGISTER,                       ARG_NONE,                           } },
	{ T_OPCODE_POP,           "pop %a",                                 POP,           { ARG_REGISTER,                       ARG_NONE,                           } },
	{ T_OPCODE_SET,           "set %a (%b|<string>|<number>)",          SET,           { ARG_REGISTER,                       ARG_REGISTER|ARG_STRING|ARG_NUMBER, } },
	{ T_OPCODE_SWAP,          "swap %a %b",                             SWAP,          { ARG_REGISTER,                       ARG_REGISTER,                       } },
	{ T_OPCODE_CALL,          "call <function>",                        CALL,          { ARG_FUNCTION,                       ARG_NONE,                           } },
	{ T_OPCODE_RET,           "ret",                                    RET,           { ARG_NONE,                           ARG_NONE,                           } },
	{ T_OPCODE_RETV,          "retv (%a|<string>|<number>)",            RET,           { ARG_REGISTER|ARG_STRING|ARG_NUMBER, ARG_NONE,                           } },
	{ T_OPCODE_CMP,           "cmp (%a|<number>) (%b|<number>)",        CMP,           { ARG_REGISTER|ARG_NUMBER,            ARG_REGISTER|ARG_NUMBER,            } },
	{ T_OPCODE_STRCMP,        "strcmp (%a|<string>) (%b|<string>)",     STRCMP,        { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_JMP,           "jmp <label>",                            JMP,           { ARG_LABEL,                          ARG_NONE,                           } },
	{ T_OPCODE_JZ,            "jz <label>",                             JZ,            { ARG_LABEL,                          ARG_NONE,                           } },
	{ T_OPCODE_JNZ,           "jnz <label>",                            JNZ,           { ARG_LABEL,                          ARG_NONE,                           } },
	{ T_OPCODE_ECHO,          "echo <string>",                          ECHO,          { ARG_STRING,                         ARG_NONE,                           } },
	{ T_OPCODE_ERR,           "err <string>",                           ERR,           { ARG_STRING,                         ARG_NONE,                           } },
	{ T_OPCODE_PERROR,        "perror <string>",                        PERROR,        { ARG_STRING,                         ARG_NONE,                           } },
	{ T_OPCODE_BAIL,          "bail",                                   BAIL,          { ARG_NONE,                           ARG_NONE,                           } },
	{ T_OPCODE_MARK,          "mark",                                   MARK,          { ARG_NONE,                           ARG_NONE,                           } },
	{ T_OPCODE_FS_STAT,       "fs.stat (%a|<string>)",                  FS_STAT,       { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_FILE_P,     "fs.file? (%a|<string>)",                 FS_FILE_P,     { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_SYMLINK_P,  "fs.symlink? (%a|<string>)",              FS_SYMLINK_P,  { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_DIR_P,      "fs.dir? (%a|<string>)",                  FS_DIR_P,      { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_CHARDEV_P,  "fs.chardev? (%a|<string>)",              FS_CHARDEV_P,  { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_BLOCKDEV_P, "fs.blockdev? (%a|<string>)",             FS_BLOCKDEV_P, { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_FIFO_P,     "fs.fifo? (%a|<string>)",                 FS_FIFO_P,     { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_SOCKET_P,   "fs.socket? (%a|<string>)",               FS_SOCKET_P,   { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_READLINK,   "fs.readlink (%a|<string>) %b",           FS_READLINK,   { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_FS_TOUCH,      "fs.touch (%a|<string>)",                 FS_TOUCH,      { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_MKDIR,      "fs.mkdir (%a|<string>)",                 FS_MKDIR,      { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_LINK,       "fs.link (%a|<string>) (%b|<string>)",    FS_LINK,       { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_FS_SYMLINK,    "fs.symlink (%a|<string>) (%b|<string>)", FS_SYMLINK,    { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_FS_UNLINK,     "fs.unlink (%a|<string>)",                FS_UNLINK,     { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_RMDIR,      "fs.rmdir (%a|<string>)",                 FS_RMDIR,      { ARG_REGISTER|ARG_STRING,            ARG_NONE,                           } },
	{ T_OPCODE_FS_RENAME,     "fs.rename (%a|<string>) (%b|<string>)",  FS_RENAME,     { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_FS_COPY,       "fs.copy (%a|<string>) (%b|<string>)",    FS_COPY,       { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_FS_CHOWN,      "fs.chown (%a|<string>) (%b|<number>)",   FS_CHOWN,      { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_NUMBER,            } },
	{ T_OPCODE_FS_CHGRP,      "fs.chgrp (%a|<string>) (%b|<number>)",   FS_CHGRP,      { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_NUMBER,            } },
	{ T_OPCODE_FS_CHMOD,      "fs.chmod (%a|<string>) (%b|<number>)",   FS_CHMOD,      { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_NUMBER,            } },
	{ T_OPCODE_FS_SHA1,       "fs.sha1 (%a|<string>) %b",               FS_SHA1,       { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_FS_GET,        "fs.get (%a|<string>) %b",                FS_GET,        { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_FS_PUT,        "fs.put (%a|<string>) (%b|<string>)",     FS_PUT,        { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_GETFILE,       "getfile (%a|<string>) (%b|<string>)",    GETFILE,       { ARG_REGISTER|ARG_STRING,            ARG_REGISTER|ARG_STRING,            } },
	{ T_OPCODE_GETUID,        "getuid (%a|<string>) %b",                GETUID,        { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_GETGID,        "getgid (%a|<string>) %b",                GETGID,        { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_EXEC,          "exec (%a|<string>) %b",                  EXEC,          { ARG_REGISTER|ARG_STRING,            ARG_REGISTER,                       } },
	{ T_OPCODE_DUMP,          "dump",                                   DUMP,          { ARG_NONE,                           ARG_NONE,                           } },
	{ T_OPCODE_HALT,          "halt",                                   HALT,          { ARG_NONE,                           ARG_NONE,                           } },
	{ 0, 0, 0, { 0, 0 } },
};
